//
//  PROLOGUE
//  ABSTRACT
//    Classification
//      UNCLASSIFIED
// 
//    Name
//      Security Banner Service Correlation Center Topic Header File
//   
//    Identifier
//      Filename:  APPSITESTATUSTopic.h
//   
//    Contract Identifier
//      ISC2 (Integrated Space Command and Control)
//  
//    Purpose
//      This file defines the JNI interface between 
//      pname.ews.theapp.bnrsbs.APPSITESTATUS.APPSITESTATUSTopic
//      and the native EWSBNR code. The guts of this file was generated by "javah -jni" on
//      pname.ews.theapp.bnrsbs.APPSITESTATUS.APPSITESTATUSTopic.class.
//   
//  DESCRIPTION
//    Error Codes Returned/Exceptions Raised
//      None.
//   
//  NOTES
//    Design Constraints
//      None.
//   
//    Special Processing
//      None.
//   
//    Side Effects
//      None.
//   
//    Performance Issues
//      None.
//   
//    Limitations
//      None.
//   
//    Target Dependencies
//      None.
//   
//    Compiler Dependencies
//      None.
//   
//  LAST REVISION
//      Date       DR Number    Login        Modification
//      =========  ===========  ===========  ======================
//      23-JAN-04  SMR0010152   dfritz       Add JNI logic to subscribe to and
//                                           receive correlation center state.
//-----------------------------------------------------------------------------
/* Header for class nuwss_ews_ewsbnr_bnrsbs_APPSITESTATUS_APPSITESTATUSTopic */
#include <jni.h>

#ifndef _Included_nuwss_ews_ewsbnr_bnrsbs_APPSITESTATUS_APPSITESTATUSTopic
#define _Included_nuwss_ews_ewsbnr_bnrsbs_APPSITESTATUS_APPSITESTATUSTopic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nuwss_ews_ewsbnr_bnrsbs_APPSITESTATUS_APPSITESTATUSTopic
 * Method:    onMessage
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_nuwss_ews_ewsbnr_bnrsbs_APPSITESTATUS_APPSITESTATUSTopic_onMessage
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
