
//-----------------------------------------------------------------------------
// APPSITESTATUS.cpp : Defines the initialization routines for the DLL.
//

#include "stdafx.h"
#include "APPSITESTATUS.h"
#include "APPSITESTATUSTopic.h"
#include "..\ewsbnrdefinitions.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

UINT UWM_CCSTATE = 0;                       // Unique message id

//
//  Note!
//
//      If this DLL is dynamically linked against the MFC
//      DLLs, any functions exported from this DLL which
//      call into MFC must have the AFX_MANAGE_STATE macro
//      added at the very beginning of the function.
//
//      For example:
//
//      extern "C" BOOL PASCAL EXPORT ExportedFunction()
//      {
//          AFX_MANAGE_STATE(AfxGetStaticModuleState());
//          // normal function body here
//      }
//
//      It is very important that this macro appear in each
//      function, prior to any calls into MFC.  This means that
//      it must appear as the first statement within the 
//      function, even before any object variable declarations
//      as their constructors may generate calls into the MFC
//      DLL.
//
//      Please see MFC Technical Notes 33 and 58 for additional
//      details.
//

/////////////////////////////////////////////////////////////////////////////
// CAPPSITESTATUSApp

BEGIN_MESSAGE_MAP(CAPPSITESTATUSApp, CWinApp)
    //{{AFX_MSG_MAP(CAPPSITESTATUSApp)
        // NOTE - the ClassWizard will add and remove mapping macros here.
        //    DO NOT EDIT what you see in these blocks of generated code!
    //}}AFX_MSG_MAP
END_MESSAGE_MAP()

/////////////////////////////////////////////////////////////////////////////
// CAPPSITESTATUSApp construction

/////////////////////////////////////////////////////
///// Constructor:  CAPPSITESTATUSApp /////
/////////////////////////////////////////////////////
//
// CAPPSITESTATUSApp::CAPPSITESTATUSApp()
//
//==
// @author  David Fritz
// @version  1.0
// Purpose: Default constructor for the class 
//
// This class was initially generated by the Visual Studio Class Wizard and 
// represents a default MFC dll. This dll implements the JNI interface declared
// in pname.ews.theapp.bnrsbs.APPSITESTATUSTopic in order to pass the
// current Correlation Center State value received in the Java environment from
// C2SNTY to EWSBNR's native code for display to the user.
//
// The only action this constructor takes is to register for the unique message
// "UWM_CCSTATE_MSG" defined in the APPSITESTATUS header file.
//
//==
CAPPSITESTATUSApp::CAPPSITESTATUSApp() {
    AFX_MANAGE_STATE(AfxGetStaticModuleState());
    UWM_CCSTATE = RegisterWindowMessage(UWM_CCSTATE_MSG);
}

/////////////////////////////////////////////////////////////////////////////
// The one and only CAPPSITESTATUSApp object

CAPPSITESTATUSApp theApp;

/////////////////////////////////////////////
/////     Function:  onMessage          /////
/////////////////////////////////////////////
//
//JNIEXPORT jboolean JNICALL 
//    Java_nuwss_ews_ewsbnr_bnrsbs_APPSITESTATUS_APPSITESTATUSTopic_onMessage
//    (JNIEnv *, jobject, jboolean) {
//
//==
// @author  David Fritz
// @version  1.0
// Purpose: This method's signature is defined by JNI (using javah.exe -jni) to
// be the JNI interface to pass the mission and assessment value from the Java
// environment to the native environment. This method validates that it knows 
// how to send the data to EWSBNR (a unique message id is known), finds the
// handle to EWSBNR's main window (which is not visible but does exist), 
// formats the information into a WPARAM DWORD (LPARAM is not used) and
// then posts the message and data to EWSBNR's application queue. If the post 
// works, this method returns a true, otherwise, false.
//
// A PostMessage method call does not block waiting for EWSBNR to process the
// message, it returns control as soon as the message is placed in EWSBNR's
// queue.
//
// @return jboolean  - JNI_TRUE = successful ; JNI_FALSE = error 
// @param jboolean - Correlation Center State (JNI_TRUE = PCC, JNI_FALSE = BCC)
//==
JNIEXPORT jboolean JNICALL 
    Java_nuwss_ews_ewsbnr_bnrsbs_APPSITESTATUS_APPSITESTATUSTopic_onMessage
    (JNIEnv *, jobject, jboolean bState) {
    AFX_MANAGE_STATE(AfxGetStaticModuleState());
    BOOL bCCState = false;

    // If the bState is true, set the native flag to true
    if (bState == JNI_TRUE)
        bCCState = true;

    if (UWM_CCSTATE != 0) {
        // find the Security Banner Service application window
        HWND DestWnd = FindWindow(NULL, CB_SECURITY_BANNER_SERVICE);

        if (DestWnd != NULL) {

            // Post the message to EWSBNR's queue
            BOOL bRes = PostMessage(DestWnd, UWM_CCSTATE, 
                MAKEWPARAM(bCCState, 0), 0);

            if (bRes)
                return JNI_TRUE;

        }
    }

    return JNI_FALSE;
}
